"""The client used to talk Modbus"""

import asyncio
import itertools
import logging
import os
import time
from typing import Any
from typing import Callable
from typing import Type
from typing import TypeVar
from typing import cast

import serial
from homeassistant.core import HomeAssistant

from .. import client
from ..common.types import ConnectionType
from ..common.types import RegisterType
from ..const import RTU_OVER_TCP
from ..const import SERIAL
from ..const import TCP
from ..const import UDP
from ..inverter_adapters import InverterAdapter
from ..vendor.pymodbus import ModbusIOException
from ..vendor.pymodbus import ModbusResponse
from ..vendor.pymodbus import ModbusRtuFramer
from ..vendor.pymodbus import ModbusSerialClient
from ..vendor.pymodbus import ModbusSocketFramer
from ..vendor.pymodbus import ModbusUdpClient
from ..vendor.pymodbus import ReadHoldingRegistersResponse
from ..vendor.pymodbus import ReadInputRegistersResponse
from ..vendor.pymodbus import WriteMultipleRegistersResponse
from ..vendor.pymodbus import WriteSingleRegisterResponse
from .custom_modbus_tcp_client import CustomModbusTcpClient

_LOGGER = logging.getLogger(__name__)

T = TypeVar("T")

# FoxESS H3 firmware Manager 1.93 answers every request with the response to the PREVIOUS request it received
# (measured 2026-09-30 through an RS485-TCP gateway: asking for 1, 2, 3.. registers returned 1, 1, 2.. registers, and
# the content matched the previous address). The gateway also polls the inverter itself, and those requests can slip
# in between ours. So each request is repeated: the first answer is always discarded, and an answer is only accepted
# once it fits the request (register count, write echo). Where the shape can't tell answers apart (single-register
# reads, exception responses) two consecutive answers must agree. The inverter has also been seen answering normally
# again (after writes on 2026-09-30); repeating the request stays correct either way, at the cost of extra bus traffic.
# read_registers_pipelined detects which of the two the inverter is doing per batch.
_LAGGED_RESPONSE_WORKAROUND = True
_LAGGED_RESPONSE_MAX_ATTEMPTS = 5


def _is_failed_exchange(response: Any) -> bool:
    """
    Whether no answer from the inverter came back: a pymodbus error (e.g. timeout), or an exception generated by the
    gateway itself (0x0A/0x0B gateway errors, or eModbus' own codes from 0xE0, e.g. 0xE0 timeout). After such an
    exchange we can't tell which request the following answers belong to.
    """
    if isinstance(response, Exception):
        return True
    return bool(response.isError() and getattr(response, "exception_code", 0) in (0x0A, 0x0B, *range(0xE0, 0x100)))


_CLIENTS: dict[str, dict[str, Any]] = {
    SERIAL: {
        "client": ModbusSerialClient,
        "framer": ModbusRtuFramer,
    },
    TCP: {
        "client": CustomModbusTcpClient,
        "framer": ModbusSocketFramer,
    },
    UDP: {
        "client": ModbusUdpClient,
        "framer": ModbusSocketFramer,
    },
    RTU_OVER_TCP: {
        "client": CustomModbusTcpClient,
        "framer": ModbusRtuFramer,
    },
}

_NUM_RETRIES = 3

serial.protocol_handler_packages.append(client.__name__)


class ModbusClient:
    """Modbus"""

    def __init__(
        self,
        hass: HomeAssistant,
        protocol: str,
        adapter: InverterAdapter,
        config: dict[str, Any],
    ) -> None:
        """Init"""
        self._hass = hass
        self._config = config
        self._lock = asyncio.Lock()
        self._protocol = protocol

        client = _CLIENTS[protocol]

        # Delaying for a second after establishing a connection seems to help the inverter stability,
        # see https://github.com/nathanmarlor/foxess_modbus/discussions/132
        config = {
            **config,
            "framer": client["framer"],
            "delay_on_connect": 1 if adapter.connection_type == ConnectionType.LAN else None,
            "retries": _NUM_RETRIES,
            # See https://github.com/nathanmarlor/foxess_modbus/discussions/792
            "retry_on_empty": True,
        }

        # If our custom PosixPollSerial hack is supported, use that. This uses poll rather than select, which means we
        # don't break when there are more than 1024 fds. See #457.
        # Only supported on posix, see https://github.com/pyserial/pyserial/blob/7aeea35429d15f3eefed10bbb659674638903e3a/serial/__init__.py#L31
        # This ties into the call to serial.protocol_handler_packages.append above, and means that pyserial will find
        # our protocol_pollserial module, and the Serial class inside, when we use the prefix pollserial://
        if protocol == SERIAL and os.name == "posix":
            config["port"] = f"pollserial://{config['port']}"

        # Some serial devices need a short delay after polling. Also do this for the inverter, just
        # in case it helps.
        self._poll_delay = 30 / 1000 if protocol == SERIAL or adapter.connection_type == ConnectionType.LAN else 0

        self._client = client["client"](**config)

    async def close(self) -> None:
        """Close connection"""
        _LOGGER.debug("Closing connection to modbus on %s", self)
        await self._async_pymodbus_call(self._client.close, auto_connect=False)

    async def read_registers(
        self,
        start_address: int,
        num_registers: int,
        register_type: RegisterType,
        slave: int,
    ) -> list[int]:
        """Read registers"""
        expected_response_type: Type[Any]
        if register_type == RegisterType.HOLDING:
            call: Callable[..., Any] = self._client.read_holding_registers
            expected_response_type = ReadHoldingRegistersResponse
            function_code = 0x03
        elif register_type == RegisterType.INPUT:
            call = self._client.read_input_registers
            expected_response_type = ReadInputRegistersResponse
            function_code = 0x04
        else:
            raise AssertionError()

        if _LAGGED_RESPONSE_WORKAROUND:

            def fits(r: Any) -> bool:
                if _is_failed_exchange(r):
                    return False
                if r.isError():
                    return getattr(r, "function_code", None) == function_code | 0x80
                return isinstance(r, expected_response_type) and len(r.registers) == num_registers

            response = await self._async_pymodbus_call_lagged(
                call,
                start_address,
                num_registers,
                slave,
                fits=fits,
                needs_confirmation=lambda r: num_registers == 1 or r.isError(),
            )
        else:
            response = await self._async_pymodbus_call(call, start_address, num_registers, slave)

        if response.isError():
            message = (
                f"Error reading registers. Type: {register_type}; start: {start_address}; count: {num_registers}; "
                f"slave: {slave}"
            )
            if isinstance(response, Exception):
                raise ModbusClientFailedError(message, self, response) from response
            raise ModbusClientFailedError(message, self, response)

        # We've seen cases where the remote device gets two requests at the same time and sends the wrong response to
        # the wrong thing. pymodbus doesn't check whether the response type matches the request type
        if not isinstance(response, expected_response_type):
            message = (
                f"Error reading registers. Type: {register_type}; start: {start_address}; count: {num_registers}; "
                f"slave: {slave}. Received incorrect response type {response}. Please ensure that your adapter is "
                "correctly configured to allow multiple connections, see the instructions at "
                "https://github.com/nathanmarlor/foxess_modbus/wiki"
            )
            # ModbusController only logs this as debug. Make this a bit clearer so people spot and fix this
            _LOGGER.warning(message)
            raise ModbusClientFailedError(
                message,
                self,
                response,
            )

        if len(response.registers) != num_registers:
            message = (
                f"Error reading registers. Type: {register_type}; start: {start_address}; count: {num_registers}; "
                f"slave: {slave}. Received {len(response.registers)} registers instead"
            )
            raise ModbusClientFailedError(message, self, response)

        return cast(list[int], response.registers)

    async def read_registers_pipelined(
        self,
        ranges: list[tuple[int, int]],
        register_type: RegisterType,
        slave: int,
    ) -> "list[list[int] | ModbusClientFailedError]":
        """
        Read several ranges in one go, see _LAGGED_RESPONSE_WORKAROUND.

        The ranges are sent back to back, one exchange each, framed by probes which show whether the inverter is
        answering one request behind or not (see below). Single-register ranges are sent twice and their two answers
        must agree: in the lagging state a request slipped in by the gateway replaces exactly one answer, and for a
        single register its shape gives nothing away. Any range whose answer doesn't fit is re-read with
        read_registers, which is correct in both states.

        Returns, per range, either the registers or the error (e.g. an exception response).
        """
        if not _LAGGED_RESPONSE_WORKAROUND or not ranges:
            results: "list[list[int] | ModbusClientFailedError]" = []
            for start_address, num_registers in ranges:
                try:
                    results.append(await self.read_registers(start_address, num_registers, register_type, slave))
                except ModbusClientFailedError as ex:
                    results.append(ex)
            return results

        if register_type == RegisterType.HOLDING:
            call: Callable[..., Any] = self._client.read_holding_registers
            expected_response_type: Type[Any] = ReadHoldingRegistersResponse
            function_code = 0x03
        elif register_type == RegisterType.INPUT:
            call = self._client.read_input_registers
            expected_response_type = ReadInputRegistersResponse
            function_code = 0x04
        else:
            raise AssertionError()

        def fits(r: Any, num_registers: int) -> bool:
            if _is_failed_exchange(r):
                return False
            if r.isError():
                return getattr(r, "function_code", None) == function_code | 0x80
            return isinstance(r, expected_response_type) and len(r.registers) == num_registers

        def agree(a: Any, b: Any) -> bool:
            return bool(a.registers == b.registers)

        # The inverter has been seen both answering one request behind and answering normally, and switching
        # between the two, so the answer for request k is either its own or the one for request k - 1. No two
        # neighbouring requests in the batch have the same length (a spacer of another length goes between them
        # where needed), so whichever of the two answers is taken for a range, it only fits if it is the range's
        # own. That holds even if the inverter switches within the batch.
        #
        # To know which answer to take, the batch is framed by two probes of different lengths from the same
        # address, (a, 1) then (a, 2), at the start and at the end. Their answers show whether each answer belongs
        # to its own request (offset 0) or to the one before (offset 1). If the start and end offsets differ, or a
        # probe answer doesn't fit either, nothing from the batch is used and every range is read on its own below.
        probe_address = next((a for a, n in ranges if n >= 2), None)
        connection_error: Exception | None = None
        if probe_address is None:
            candidates: list[list[Any]] = [[] for _ in ranges]
            responses: list[Any] = []
        else:
            probe_1, probe_2, spacer_1, spacer_2 = -1, -2, -3, -4
            extra_requests = {
                probe_1: (probe_address, 1),
                probe_2: (probe_address, 2),
                spacer_1: (probe_address, 1),
                spacer_2: (probe_address, 2),
            }

            def request(i: int) -> tuple[int, int]:
                return extra_requests[i] if i < 0 else ranges[i]

            # Alternating blocks and single-register ranges keeps the number of spacers down
            blocks = [[i] for i, (_, n) in enumerate(ranges) if n >= 2]
            singles = [[i, i] for i, (_, n) in enumerate(ranges) if n == 1]
            body = [probe_1, probe_2]
            pair: tuple[list[int], list[int]]
            for pair in itertools.zip_longest(blocks, singles, fillvalue=[]):
                body += pair[0] + pair[1]
            body += [probe_1, probe_2]
            sequence: list[int] = []
            for i in body:
                # Repeats of the same single-register range are meant to give the same answer
                if sequence and sequence[-1] != i and request(sequence[-1])[1] == request(i)[1]:
                    sequence.append(spacer_2 if request(i)[1] == 1 else spacer_1)
                sequence.append(i)
            # The final repeat fetches the last probe's answer when the inverter answers one request behind
            sequence.append(probe_2)

            def _call() -> list[Any]:
                if not self._client.connected:
                    self._client.connect()
                answers: list[Any] = []
                for i in sequence:
                    if answers and self._poll_delay > 0:
                        time.sleep(self._poll_delay)
                    start_address, num_registers = request(i)
                    answers.append(call(start_address, num_registers, slave))
                    # No connection (e.g. timeout): the rest of the batch would only wait for timeouts as well
                    if isinstance(answers[-1], Exception):
                        break
                return answers

            async with self._lock:
                responses = await self._hass.async_add_executor_job(_call)
                if self._poll_delay > 0:
                    await asyncio.sleep(self._poll_delay)

            def offset_at(j: int) -> int | None:
                """Offset shown by the probe pair whose first request is sequence[j]"""
                for offset in (0, 1):
                    first, second = responses[j + offset], responses[j + 1 + offset]
                    if fits(first, 1) and not first.isError() and fits(second, 2) and not second.isError():
                        return offset
                return None

            candidates = [[] for _ in ranges]
            if len(responses) < len(sequence):
                connection_error = responses[-1]
                offsets: set[int | None] = set()
            else:
                offsets = {offset_at(j) for j, i in enumerate(sequence) if i == probe_1}
            if len(offsets) == 1 and None not in offsets:
                offset = offsets.pop()
                assert offset is not None
                for j, i in enumerate(sequence[:-1]):
                    # After a failed exchange we can't be sure which answer belongs to which request
                    if any(_is_failed_exchange(r) for r in responses[: j + offset + 1]):
                        break
                    if i >= 0:
                        candidates[i].append(responses[j + offset])
            else:
                _LOGGER.debug(
                    "Pipelined read on %s: probe offsets %s, reading each range on its own",
                    self,
                    offsets,
                )

        results = []
        for (start_address, num_registers), answers in zip(ranges, candidates, strict=True):
            needed = 2 if num_registers == 1 else 1
            # An exception response has no length to tell whose it is, so it is confirmed by read_registers
            accepted = (
                len(answers) == needed
                and all(fits(a, num_registers) and not a.isError() for a in answers)
                and (needed == 1 or agree(answers[0], answers[1]))
            )
            if not accepted:
                if connection_error is not None:
                    # Like reading range by range: the first connection error ends the poll
                    message = (
                        f"Error reading registers. Type: {register_type}; start: {start_address}; "
                        f"count: {num_registers}; slave: {slave}"
                    )
                    results.append(ModbusClientFailedError(message, self, connection_error))
                    continue
                _LOGGER.debug(
                    "Re-reading (%s, %s) on %s: pipelined answer rejected",
                    start_address,
                    num_registers,
                    self,
                )
                try:
                    results.append(await self.read_registers(start_address, num_registers, register_type, slave))
                except ModbusClientFailedError as ex:
                    results.append(ex)
                    if isinstance(ex.response, Exception):
                        connection_error = ex.response
                continue
            results.append(cast(list[int], answers[-1].registers))
        return results

    async def write_registers(self, register_address: int, register_values: list[int], slave: int) -> None:
        """Write registers"""
        expected_response_type: Type[Any]
        if len(register_values) > 1:
            register_values = [int(i) for i in register_values]
            call: Callable[..., Any] = self._client.write_registers
            value: Any = register_values
            expected_response_type = WriteMultipleRegistersResponse
            function_code = 0x10

            def echo_matches(r: Any) -> bool:
                return bool(r.address == register_address and r.count == len(register_values))

        else:
            call = self._client.write_register
            value = int(register_values[0])
            expected_response_type = WriteSingleRegisterResponse
            function_code = 0x06

            def echo_matches(r: Any) -> bool:
                return bool(r.address == register_address and r.value == value)

        if _LAGGED_RESPONSE_WORKAROUND:
            # Repeating a write sends the same value again, which the inverter just applies again

            def fits(r: Any) -> bool:
                if _is_failed_exchange(r):
                    return False
                if r.isError():
                    return getattr(r, "function_code", None) == function_code | 0x80
                return isinstance(r, expected_response_type) and echo_matches(r)

            response = await self._async_pymodbus_call_lagged(
                call,
                register_address,
                value,
                slave,
                fits=fits,
                needs_confirmation=lambda r: r.isError(),
            )
        else:
            response = await self._async_pymodbus_call(call, register_address, value, slave)

        if response.isError():
            message = f"Error writing registers. Start: {register_address}; values: {register_values}; slave: {slave}"
            if isinstance(response, Exception):
                raise ModbusClientFailedError(message, self, response) from response
            raise ModbusClientFailedError(message, self, response)

        # We've seen cases where the remote device gets two requests at the same time and sends the wrong response to
        # the wrong thing. pymodbus doesn't check whether the response type matches the request type
        if not isinstance(response, expected_response_type):
            message = (
                f"Error writing registers. Start: {register_address}; values: {register_values}; slave: {slave}. "
                f"Received incorrect response type {response}. Please ensure that your adapter is correctly "
                "configured to allow multiple connections, see the instructions at "
                "https://github.com/nathanmarlor/foxess_modbus/wiki"
            )
            raise ModbusClientFailedError(
                message,
                self,
                response,
            )

        if not echo_matches(response):
            message = (
                f"Error writing registers. Start: {register_address}; values: {register_values}; slave: {slave}. "
                f"Received a confirmation for another write: {response}"
            )
            raise ModbusClientFailedError(message, self, response)

    async def _async_pymodbus_call(self, call: Callable[..., T], *args: Any, auto_connect: bool = True) -> T:
        """Convert async to sync pymodbus call."""

        def _call() -> T:
            # When using pollserial://, connected calls into serial.serial_for_url, which calls importlib.import_module,
            # which HA doesn't like (see https://github.com/nathanmarlor/foxess_modbus/issues/618).
            # Therefore we need to do this check inside the executor job
            if auto_connect and not self._client.connected:
                self._client.connect()
            # If the connection failed, this call will throw an appropriate error
            return call(*args)

        async with self._lock:
            result = await self._hass.async_add_executor_job(_call)
            # This seems to be required for serial devices, otherwise subsequent reads fail
            # The HA modbus integration does the same
            if self._poll_delay > 0:
                await asyncio.sleep(self._poll_delay)
            return result

    async def _async_pymodbus_call_lagged(
        self,
        call: Callable[..., T],
        *args: Any,
        fits: Callable[[T], bool],
        needs_confirmation: Callable[[T], bool],
    ) -> T | ModbusIOException:
        """
        Repeat a pymodbus call until the answer belongs to it, see _LAGGED_RESPONSE_WORKAROUND.

        All repeats happen under one lock acquisition, so none of our own requests can get in between. Returns a
        ModbusIOException if no answer was accepted, for the caller's normal validation to report. That is never
        an IllegalAddress exception response, so the controller doesn't mark the registers as invalid.
        """

        def agree(a: Any, b: Any) -> bool:
            if type(a) is not type(b):
                return False
            if a.isError():
                return bool(getattr(a, "exception_code", None) == getattr(b, "exception_code", None))
            return bool(getattr(a, "registers", None) == getattr(b, "registers", None))

        def _call() -> T | ModbusIOException:
            if not self._client.connected:
                self._client.connect()
            responses: list[T] = []
            for attempt in range(_LAGGED_RESPONSE_MAX_ATTEMPTS):
                if attempt > 0 and self._poll_delay > 0:
                    time.sleep(self._poll_delay)
                response = call(*args)
                responses.append(response)
                # No connection (e.g. timeout): repeating only waits for more timeouts. The gateway's own error
                # codes are exception responses instead, and are repeated
                if isinstance(response, Exception):
                    return response
                # The first answer belongs to whatever the inverter was asked before
                if attempt == 0 or not fits(response):
                    continue
                if not needs_confirmation(response):
                    return response
                if attempt >= 2 and fits(responses[-2]) and agree(response, responses[-2]):
                    return response
            _LOGGER.debug(
                "No answer to %s%s on %s was accepted after %s attempts",
                call,
                args,
                self,
                len(responses),
            )
            return ModbusIOException(f"No answer was accepted after {len(responses)} attempts")

        async with self._lock:
            result = await self._hass.async_add_executor_job(_call)
            if self._poll_delay > 0:
                await asyncio.sleep(self._poll_delay)
            return result

    def __str__(self) -> str:
        if self._protocol == SERIAL:
            return f"{self._config['port']}"
        return f"{self._protocol}://{self._config['host']}:{self._config['port']}"


class ModbusClientFailedError(Exception):
    """Raised when the ModbusClient fails to read/write"""

    def __init__(self, message: str, client: ModbusClient, response: ModbusResponse | Exception) -> None:
        super().__init__(f"{message} from {client}: {response}")
        self.message = message
        self.client = client
        self.response = response

    def __str__(self) -> str:
        return f"{self.message} from {self.client}: {self.response}"
